import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import { contentHash, verifyContentHash } from '../domain/content-hash.ts';
import type { NodeInput } from '../repository/node-repository.ts';
import type {
  NodeConstraint,
  NodeParameter,
  NodeRelationship,
  SekkeiNode,
  Stratum,
} from '../types.ts';

/**
 * Maps a node + its supporting rows to a single YAML file at
 *
 *   <repoRoot>/nodes/<stratum>/<safe-glm-id>.yaml
 *
 * where `safe-glm-id` is the glm_id with `:` replaced by `__` so the path
 * is portable to Windows. The transform is reversible (`__` is otherwise
 * disallowed in our glm_id grammar).
 *
 * Key ordering is fixed at write time to keep the diff stable across
 * authors. The hash stored in the file body must match
 * `contentHash(body)`; readers throw if it does not.
 */

export interface YamlNode {
  id: string;
  stratum: Stratum;
  title: string;
  description: string;
  revision: { major: string; iteration: number; status: SekkeiNode['revisionStatus'] };
  override_kind: SekkeiNode['overrideKind'];
  derives_from: string | null;
  system_role: string | null;
  spec_kind: string | null;
  authored_by: string;
  authored_at: string;
  body: Record<string, unknown>;
  parameters?: Array<Omit<NodeParameter, 'nodeId'>>;
  constraints?: Array<Omit<NodeConstraint, 'nodeId'>>;
  relationships?: Array<Omit<NodeRelationship, 'sourceNodeId'>>;
  content_hash: string;
}

export class YamlStoreError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'YamlStoreError';
  }
}

const HEADER = '# generated by glm — content_hash is authoritative; manual edits should re-run the verifier\n';

/** Absolute path for the YAML file representing this node. */
export function nodeFilePath(repoRoot: string, stratum: Stratum, glmId: string): string {
  return join(repoRoot, 'nodes', stratum, `${safeGlmId(glmId)}.yaml`);
}

export function safeGlmId(glmId: string): string {
  return glmId.replace(/:/g, '__');
}

/** Serialize a node to canonical YAML. Caller writes to disk. */
export function serializeNode(node: SekkeiNode, opts: {
  parameters?: NodeParameter[];
  constraints?: NodeConstraint[];
  relationships?: NodeRelationship[];
} = {}): string {
  const recomputed = contentHash(node.body);
  if (recomputed !== node.contentHash) {
    throw new YamlStoreError(
      `content_hash on node disagrees with body: stored=${node.contentHash}, recomputed=${recomputed}`,
    );
  }
  const yamlNode: YamlNode = {
    id: node.glmId,
    stratum: node.stratum,
    title: node.title,
    description: node.description,
    revision: {
      major: node.revisionMajor,
      iteration: node.revisionIteration,
      status: node.revisionStatus,
    },
    override_kind: node.overrideKind,
    derives_from: node.derivesFromNodeId,
    system_role: node.systemRole,
    spec_kind: node.specKind,
    authored_by: node.authoredBy,
    authored_at: node.authoredAt,
    body: node.body as Record<string, unknown>,
    content_hash: node.contentHash,
  };
  if (opts.parameters && opts.parameters.length > 0) {
    yamlNode.parameters = opts.parameters.map(stripNodeId);
  }
  if (opts.constraints && opts.constraints.length > 0) {
    yamlNode.constraints = opts.constraints.map(stripNodeId);
  }
  if (opts.relationships && opts.relationships.length > 0) {
    yamlNode.relationships = opts.relationships.map((r) => {
      const { sourceNodeId, ...rest } = r;
      void sourceNodeId;
      return rest;
    });
  }

  return HEADER + stringifyYaml(yamlNode, { lineWidth: 0, indent: 2 });
}

/** Parse a YAML file back into a structured node. Verifies content_hash. */
export function parseNode(text: string): YamlNode {
  const value = parseYaml(text) as YamlNode | null;
  if (!value || typeof value !== 'object') throw new YamlStoreError('node YAML must be a mapping');
  if (typeof value.id !== 'string') throw new YamlStoreError('node YAML missing id');
  if (!verifyContentHash(value.body, value.content_hash)) {
    throw new YamlStoreError(`content_hash mismatch in YAML for ${value.id}`);
  }
  return value;
}

/** Convert a parsed YAML node into the repository's `NodeInput` shape. */
export function yamlToNodeInput(yaml: YamlNode, workspaceId: string, id: string): NodeInput {
  return {
    id,
    workspaceId,
    glmId: yaml.id,
    stratum: yaml.stratum,
    title: yaml.title,
    description: yaml.description,
    body: yaml.body,
    revisionMajor: yaml.revision.major,
    revisionIteration: yaml.revision.iteration,
    revisionStatus: yaml.revision.status,
    overrideKind: yaml.override_kind,
    derivesFromNodeId: yaml.derives_from,
    systemRole: yaml.system_role,
    specKind: yaml.spec_kind,
    authoredBy: yaml.authored_by,
    authoredAt: yaml.authored_at,
    generatorIdentity: null,
    parameters: yaml.parameters,
    constraints: yaml.constraints,
    relationships: yaml.relationships,
  };
}

/** Write a node to its canonical path under `repoRoot`. Creates dirs as needed. */
export function writeNodeFile(
  repoRoot: string,
  node: SekkeiNode,
  children: { parameters?: NodeParameter[]; constraints?: NodeConstraint[]; relationships?: NodeRelationship[] } = {},
): string {
  const path = nodeFilePath(repoRoot, node.stratum, node.glmId);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, serializeNode(node, children), 'utf8');
  return path;
}

/** Read a node YAML file (if present) and parse it. */
export function readNodeFile(repoRoot: string, stratum: Stratum, glmId: string): YamlNode | null {
  const path = nodeFilePath(repoRoot, stratum, glmId);
  if (!existsSync(path)) return null;
  return parseNode(readFileSync(path, 'utf8'));
}

function stripNodeId<T extends { nodeId: string }>(v: T): Omit<T, 'nodeId'> {
  const { nodeId: _id, ...rest } = v;
  void _id;
  return rest as Omit<T, 'nodeId'>;
}
