import { VERSION } from '../version.ts';

const USAGE = `glm — GLM Solo CLI v${VERSION}

USAGE
  glm <command> [options]

COMMANDS
  vibe [--workspace <id>] [--from-dir <path>] [--description-file <file>]
                          Author or reverse-engineer a sekkei interactively.

  verify [--workspace <id>] [--verbose] [--no-color]
                          Run the 6 verifier gates and print per-gate results.
                          Exit 0 on overall pass, 1 on any gate failure.

  generate --component <id> [--workspace <id>] [--dry-run]
                          Generate output files for one Component from its spec.prompt.

  import-sekkei <file.yaml> [--workspace <id>]
                          Import a sekkei YAML file into the workspace.

  refine --node <id> [--workspace <id>]
                          Interactively refine a node's body using Claude CLI.

  init [--name <name>] [--port <port>] [--token <hex>] [--force]
                          Generate ~/.glm/config.json with a random GLM_SOLO_TOKEN.
                          Set that token as an env var on the GLM server to enable
                          solo-mode auth bypass.

  status [--workspace <id>]
                          Show sekkei node counts, verification status, last generation timestamp.

GLOBAL OPTIONS
  --port <port>           GLM server port (default 3000; or env PORT).
  --workspace <id>        Workspace id (default "default"; or env GLM_WORKSPACE).
  --token <token>         Solo-mode auth token (or env GLM_SOLO_TOKEN).
  --model <model>         Override Claude model (default claude-sonnet-4-6; or env GLM_CLAUDE_MODEL).
  --json                  Emit machine-readable JSON instead of human-formatted text.
  --help, -h              Show this help message.
  --version, -v           Show CLI version.

ENVIRONMENT
  PORT                    Default port for the GLM server.
  GLM_WORKSPACE           Default workspace id.
  GLM_SOLO_TOKEN          Solo-mode auth token (32-byte hex; generated by 'glm init').
  GLM_CLAUDE_MODEL        Default Claude model passed to 'claude --model'.
  GLM_REPO_ROOT           Path to the GLM repo (for sekkei-authoring.md + schema lookup).
                          Auto-detected from the binary location if not set.

DOCUMENTATION
  Spec:           docs/solo-mode-spec.md
  Authoring:      docs/sekkei-authoring.md
  User manual:    docs/user-manual.md
  Plan:           integrations/cli/IMPLEMENTATION_PLAN.md
`;

export function runHelp(): void {
  process.stdout.write(USAGE);
}

export function runVersion(): void {
  process.stdout.write(`${VERSION}\n`);
}
